name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: make windows
        run: make windows
      - name: app
        run: app
  
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make linux
        run: make linux
      - name: app
        run: app
  
  windows-debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: make windows-debug
        run: make windows-debug
      - name: app
        run: app
  
  linux-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make linux-debug
        run: make linux-debug
      - name: app
        run: app
