name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows-debug:
    runs-on: windows-latest
    steps:
    - name: make windows-debug
      run: make windows-debug
  
  windows:
    runs-on: windows-latest
    steps:
    - name: make windows
      run: make windows
  
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: make linux
      run: make linux
